propose:
  description: >
    You're proposing the motion for a debate on the motion: {motion}. Come up with 
    clear arguments in favor of the motion.
    Be very convincing.
  expected_output: >
    Your clear argument in favor of the motion, in a concise manner.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    You're the opposition to the motion for a debate on the motion: {motion}. Come up with clear and convincing arguments against the motion.
    Be very convincing.
  expected_output: >
    Your clear argument against the motion, in a concise manner.
  agent: debater
  output_file: output/oppose.md

decide:
  description: >
    You're deciding the winner of the debate based on the arguments presented for and against the motion: {motion}.
    Be very impartial and base your decision purely on the arguments presented.
  expected_output: >
    Your decision on which side is more convincing, in a concise manner.
  agent: judge
  output_file: output/decide.md